### ISSUE TITLE
chromatogram plots are fixed to page

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#126]
The chromatogram plots should be fixed in size.  Currently they are fixed to a page.  Here are two examples.  They both should show 384 plots that are fixed in size.  Instead they show less than 384 plots and they are fixed to a page.  
[ABMBA_positive_4p80-385_1column.pdf](https://github.com/biorack/metatlas/files/317354/ABMBA_positive_4p80-385_1column.pdf)
[ABMBA_positive_4p80-385.pdf](https://github.com/biorack/metatlas/files/317353/ABMBA_positive_4p80-385.pdf)

**Comment by aitatanit** [comment]
The pickle file that I will be creating generated these plots?

**Comment by benbowen** [comment]
Yes

**Comment by benbowen** [comment]
This is the example to model your results after.  
[Chromatograms_Violacein_Pos_20150819_new_groupnames_lumped_isomers tryptophan.pdf](https://github.com/biorack/metatlas/files/320693/Chromatograms_Violacein_Pos_20150819_new_groupnames_lumped_isomers.tryptophan.pdf)

**Comment by aitatanit** [comment]
Here's a first cut. Still working on the y-tick marks and the title. I noticed that the rt_max can be larger than max(x) in some instances. BTW, The time to construct these plots has increased due to the annotations I am doing:
file_names =  28
compounds per file =  50
time ~ 90 secs

How is the resolution on this plot?

[20160504_RL_HMArkin_CA-MF_6550_HILICNeg_CA2A_1_007rerun.h5-51-30x30.pdf](https://github.com/biorack/metatlas/files/347126/20160504_RL_HMArkin_CA-MF_6550_HILICNeg_CA2A_1_007rerun.h5-51-30x30.pdf)

**Comment by benbowen** [comment]
Looking better! I noticed there aren't titles on the first row of plots.

**Comment by aitatanit** [comment]
Still working on it

**Comment by benbowen** [comment]
Fixed
